config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.MainView.as_view(), name="index"),
    path("base/", views.BaseView.as_view(), name="base"),
    path("bio/", views.BioView.as_view(), name="bio"),
    path("blog/<int:pk>", views.BlogView.as_view(), name="blog"),
    path("prod/", views.ProdView.as_view(), name="prod"),
]

main/models.py
from django.db import models
from django.utils import timezone


class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.title

main/views.py
from pyexpat import model
from re import template
from django.shortcuts import render
from django.views.generic import *
from .models import *


class BaseView(TemplateView):
    template_name = "base.html"


class MainView(ListView):
    template_name = "main/index.html"
    model = Blog
    ordering = ['-date']
    paginate_by = 5


class BioView(TemplateView):
    template_name = "main/bio.html"


class BlogView(DetailView):
    template_name = "main/blog.html"
    model = Blog


class ProdView(TemplateView):
    template_name = "main/prod.html"

templates/base.html
<!doctype html>
<html lang="ja">

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type='text/css' href="{% static 'main/css/style.css'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- FontAwesomeの読み込み -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <title>Yusaku's Portfolio</title>
</head>

<body>
    <header class="d-flex align-items-center justify-content-center bg-secondary">
        <nav class="navbar navbar-expand-md navbar-light">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi"
                aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="bs-navi">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'index' %}">TOP</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'bio' %}">BIO</a></li>
                    <li class="nav-item"><a class="nav-link text-white" href="{% url 'prod' %}">PRODUCTS</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        {% block content %}

        {% endblock content %}
    </main>

    <footer>
        <p class=" footer-text">© All rights reserved by Yusaku Nokubi</p>
    </footer>
</body>

</html>

templates/main/bio.html
{% extends "../base.html" %}

{% block content %}
<main>
    <section class="page">
        <section id="profile">
            <h2>プロフィール</h2>
            <hr>
            <div class="name">野首 侑作</div>
            <div class="">名古屋工業大学情報工学科4年 佐藤・坂上研究室</div>
        </section>
        <section id="skill">
            <h2>スキル</h2>
            <hr>
            <h3>Java</h3>
            <li>経験：2019年9月~</li>
            <li>用途：大学課題・競プロ</li>
            <h3>Unity</h3>
            <li>経験：2021年5月~</li>
            <li>用途：インターン・ハッカソン・ゲーム作成</li>
            <h3>JavaScript</h3>
            <li>経験：2020年4月~</li>
            <li>用途：ポートフォリオ・ビジコン</li>
            <h3>Python</h3>
            <li>経験年数：2020年7月~</li>
            <li>用途：機械学習・データ分析</li>
            <h3>Django</h3>
            <li>経験：2021年9月~</li>
            <li>用途：ポートフォリオ・ビジコン・趣味</li>
            <h3>Ruby on Rails</h3>
            <li>経験：2020年10月~</li>
            <li>用途：DMM WebCampモニター生</li>
            <h3>Adode</h3>
            <li>経験：2021年4月~</li>
            <li>用途：映像作成(Premiere Pro・After Effects)、画像加工(Photoshop・Illustrator)</li>
        </section>
    </section>
</main>
{% endblock content %}

templates/main/blog.html
{% extends "../base.html" %}

{% block content %}
<section>
    <div class="date">投稿日：{{ blog.date}}</div>
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="content">{{ blog.content}}</div>
</section>
{% endblock content %}

templates/main/index.html
{% extends '../base.html' %}

{% block content %}
<div class="d-flex justify-content-around">
    <div>
        <section>
            <h1>BLOG</h1>
            {% for blog in blog_list %}
            <div class="bg-light m-2 p-3">
                <a href="{% url 'blog' blog.pk %}">
                    <div class="mb-2">{{ blog.date }}</div>
                    <h4>{{ blog.title }}</h4>
                </a>
            </div>
            {% endfor %}

            <div class="d-flex justify-content-center">
                <ul class="pagination">
                    <!-- 前へ  -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- ページ番号 -->
                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                    {% endfor %}

                    <!-- 次へ -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </section>
    </div>
    <div>
        <section>
            <h1>LINK</h1>
            <div class="SNS">
                <a href="https://twitter.com/saku3449?ref_src=twsrc%5Etfw" class="twitter-follow-button"
                    data-show-count="false">Follow @saku3449</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><br>
                <a target="black" href="https://github.com/Saku3449" class="fab fa-github">Saku3449</a><br>
                <a target="black" href="https://www.wantedly.com/id/saku3449">Wantedly</a>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

templates/main/prod.html
{% extends "../base.html" %}

{% block content %}

{% endblock content %}